// Generated from src/lib/cfbTeams.js so backend odds normalization uses the same CFB team vocabulary as the frontend.
import { normalizeText } from './sharpOddsCommon.ts';

export type CfbTeamDef = { abbr: string; name: string; aliases: string[] };
export const CFB_TEAMS: CfbTeamDef[] = [
  { abbr: 'AF', name: 'Air Force Falcons', aliases: ['AF','Air Force','Air Force Falcons','AirForce'] },
  { abbr: 'AKR', name: 'Akron Zips', aliases: ['AKR','Akron','Akron Zips'] },
  { abbr: 'ALA', name: 'Alabama Crimson Tide', aliases: ['ALA','Alabama','Alabama Crimson Tide'] },
  { abbr: 'APP', name: 'Appalachian State Mountaineers', aliases: ['APP','Appalachian State','Appalachian State Mountaineers','AppalachianState'] },
  { abbr: 'ARIZ', name: 'Arizona Wildcats', aliases: ['ARIZ','Arizona','Arizona Wildcats'] },
  { abbr: 'ASU', name: 'Arizona State Sun Devils', aliases: ['ASU','Arizona State','Arizona State Sun Devils','ArizonaState'] },
  { abbr: 'ARK', name: 'Arkansas Razorbacks', aliases: ['ARK','Arkansas','Arkansas Razorbacks'] },
  { abbr: 'ARST', name: 'Arkansas State Red Wolves', aliases: ['ARST','Arkansas State','Arkansas State Red Wolves','ArkansasState'] },
  { abbr: 'ARMY', name: 'Army Black Knights', aliases: ['ARMY','Army','Army Black','Army Black Knights'] },
  { abbr: 'APSU', name: 'Austin Peay Governors', aliases: ['APSU','Austin Peay','Austin Peay Governors','Austin Peay State','Austin Peay State Governors','Austin Peay State University','Governors'] },
  { abbr: 'AUB', name: 'Auburn Tigers', aliases: ['AUB','Auburn','Auburn Tigers'] },
  { abbr: 'BALL', name: 'Ball State Cardinals', aliases: ['BALL','Ball State','Ball State Cardinals','BallState'] },
  { abbr: 'BAY', name: 'Baylor Bears', aliases: ['BAY','Baylor','Baylor Bears'] },
  { abbr: 'BCU', name: 'Bethune-Cookman Wildcats', aliases: ['BCU','B-CU','Bethune-Cookman','Bethune Cookman','Bethune-Cookman Wildcats','Bethune Cookman Wildcats','Bethune-Cookman University'] },
  { abbr: 'BSU', name: 'Boise State Broncos', aliases: ['BSU','Boise State','Boise State Broncos','BoiseState'] },
  { abbr: 'BC', name: 'Boston College Eagles', aliases: ['BC','Boston College','Boston College Eagles','BostonCollege'] },
  { abbr: 'BGSU', name: 'Bowling Green Falcons', aliases: ['BGSU','Bowling Green','Bowling Green Falcons','BowlingGreen'] },
  { abbr: 'BUFF', name: 'Buffalo Bulls', aliases: ['BUFF','Buffalo','Buffalo Bulls'] },
  { abbr: 'BUCK', name: 'Bucknell Bison', aliases: ['BUCK','Bucknell','Bucknell Bison','Bucknell University'] },
  { abbr: 'BYU', name: 'BYU Cougars', aliases: ['BYU','BYU Cougars'] },
  { abbr: 'CAL', name: 'California Golden Bears', aliases: ['CAL','California','California Golden Bears'] },
  { abbr: 'CAMP', name: 'Campbell Fighting Camels', aliases: ['CAMP','Campbell','Campbell Fighting Camels','Campbell University','Fighting Camels','Camels'] },
  { abbr: 'CP', name: 'Cal Poly Mustangs', aliases: ['CP','Cal Poly','Cal Poly Mustangs','Cal Poly SLO','Cal Poly San Luis Obispo','California Polytechnic','California Polytechnic State University'] },
  { abbr: 'CMU', name: 'Central Michigan Chippewas', aliases: ['CMU','Central Michigan','Central Michigan Chippewas','CentralMichigan'] },
  { abbr: 'CLT', name: 'Charlotte 49ers', aliases: ['CLT','Charlotte','Charlotte 49ers'] },
  { abbr: 'CIN', name: 'Cincinnati Bearcats', aliases: ['CIN','Cincinnati','Cincinnati Bearcats'] },
  { abbr: 'CLEM', name: 'Clemson Tigers', aliases: ['CLEM','Clemson','Clemson Tigers'] },
  { abbr: 'CCU', name: 'Coastal Carolina Chanticleers', aliases: ['CCU','Coastal Carolina','Coastal Carolina Chanticleers','CoastalCarolina'] },
  { abbr: 'COLO', name: 'Colorado Buffaloes', aliases: ['COLO','Colorado','Colorado Buffaloes'] },
  { abbr: 'CSU', name: 'Colorado State Rams', aliases: ['CSU','Colorado State','Colorado State Rams','ColoradoState'] },
  { abbr: 'DEL', name: 'Delaware Blue Hens', aliases: ['DEL','Delaware','Delaware Blue Hens'] },
  { abbr: 'DUKE', name: 'Duke Blue Devils', aliases: ['DUKE','Duke','Duke Blue Devils'] },
  { abbr: 'ECU', name: 'East Carolina Pirates', aliases: ['ECU','East Carolina','East Carolina Pirates','EastCarolina'] },
  { abbr: 'EKU', name: 'Eastern Kentucky Colonels', aliases: ['EKU','Eastern Kentucky','Eastern Kentucky Colonels','Eastern Kentucky University','Eastern Kentucky St','Eastern Ky','EasternKentucky','EasternKy'] },
  { abbr: 'EMU', name: 'Eastern Michigan Eagles', aliases: ['EMU','Eastern Michigan','Eastern Michigan Eagles','EasternMichigan'] },
  { abbr: 'FLA', name: 'Florida Gators', aliases: ['FLA','Florida','Florida Gators'] },
  { abbr: 'FAU', name: 'Florida Atlantic Owls', aliases: ['FAU','FAU Owls','FATL','FLA ATL','Florida Atlantic','Florida Atlantic Owls','Florida Atlantic University','Florida Atlantic University Owls','FloridaAtlantic'] },
  { abbr: 'FIU', name: 'FIU Panthers', aliases: ['FIU','FIU Panthers','FloridaInternational'] },
  { abbr: 'FSU', name: 'Florida State Seminoles', aliases: ['FSU','Florida State','Florida State Seminoles','FloridaState'] },
  { abbr: 'FRES', name: 'Fresno State Bulldogs', aliases: ['FRES','Fresno State','Fresno State Bulldogs','FresnoState'] },
  { abbr: 'UGA', name: 'Georgia Bulldogs', aliases: ['Georgia','Georgia Bulldogs','UGA'] },
  { abbr: 'GASO', name: 'Georgia Southern Eagles', aliases: ['GASO','Georgia Southern','Georgia Southern Eagles','GeorgiaSouthern'] },
  { abbr: 'GAST', name: 'Georgia State Panthers', aliases: ['GAST','Georgia State','Georgia State Panthers','GeorgiaState'] },
  { abbr: 'GT', name: 'Georgia Tech Yellow Jackets', aliases: ['GT','Georgia Tech','Georgia Tech Yellow Jackets','GeorgiaTech'] },
  { abbr: 'HAW', name: 'Hawai‘i Rainbow Warriors', aliases: ['HAW','Hawaii','Hawai‘i','Hawai‘i Rainbow Warriors'] },
  { abbr: 'HOU', name: 'Houston Cougars', aliases: ['HOU','Houston','Houston Cougars'] },
  { abbr: 'HOW', name: 'Howard Bison', aliases: ['HOW','Howard','Howard Bison','Howard University'] },
  { abbr: 'ILL', name: 'Illinois Fighting Illini', aliases: ['ILL','Illinois','Illinois Fighting Illini'] },
  { abbr: 'IND', name: 'Indiana Hoosiers', aliases: ['IND','Indiana','Indiana Hoosiers'] },
  { abbr: 'IOWA', name: 'Iowa Hawkeyes', aliases: ['IOWA','IOW','Iowa','Iowa Hawkeye','Iowa Hawkeyes','University of Iowa'] },
  { abbr: 'ISU', name: 'Iowa State Cyclones', aliases: ['ISU','Iowa State','Iowa State Cyclones','IowaState'] },
  { abbr: 'JVST', name: 'Jacksonville State Gamecocks', aliases: ['JVST','JXST','JAXST','JSU','Jacksonville State','Jacksonville State Gamecocks','JacksonvilleState'] },
  { abbr: 'JMU', name: 'James Madison Dukes', aliases: ['JMU','James Madison','James Madison Dukes','JamesMadison'] },
  { abbr: 'KU', name: 'Kansas Jayhawks', aliases: ['KU','Kansas','Kansas Jayhawks'] },
  { abbr: 'KSU', name: 'Kansas State Wildcats', aliases: ['KSU','Kansas State','Kansas State Wildcats','KansasState'] },
  { abbr: 'KENN', name: 'Kennesaw State Owls', aliases: ['KENN','Kennesaw State','Kennesaw State Owls','KennesawState'] },
  { abbr: 'KENT', name: 'Kent State Golden Flashes', aliases: ['KENT','Kent State','Kent State Golden Flashes','KentState'] },
  { abbr: 'UK', name: 'Kentucky Wildcats', aliases: ['Kentucky','Kentucky Wildcats','UK'] },
  { abbr: 'LIB', name: 'Liberty Flames', aliases: ['LIB','Liberty','Liberty Flames'] },
  { abbr: 'UL', name: 'Louisiana Ragin’ Cajuns', aliases: ['Louisiana','Louisiana Ragin’ Cajuns','UL'] },
  { abbr: 'ULM', name: 'UL Monroe Warhawks', aliases: ['LouisianaMonroe','UL Monroe','UL Monroe Warhawks','ULM'] },
  { abbr: 'LT', name: 'Louisiana Tech Bulldogs', aliases: ['LT','Louisiana Tech','Louisiana Tech Bulldogs','LouisianaTech'] },
  { abbr: 'LOU', name: 'Louisville Cardinals', aliases: ['LOU','Louisville','Louisville Cardinals'] },
  { abbr: 'LSU', name: 'LSU Tigers', aliases: ['LSU','LSU Tigers'] },
  { abbr: 'MRSH', name: 'Marshall Thundering Herd', aliases: ['MRSH','Marshall','Marshall Thundering Herd'] },
  { abbr: 'MD', name: 'Maryland Terrapins', aliases: ['MD','Maryland','Maryland Terrapins'] },
  { abbr: 'MEM', name: 'Memphis Tigers', aliases: ['MEM','Memphis','Memphis Tigers'] },
  { abbr: 'MIA', name: 'Miami Hurricanes', aliases: ['MIA','Miami Hurricanes','MiamiFL'] },
  { abbr: 'M-OH', name: 'Miami (OH) RedHawks', aliases: ['M-OH','Miami (OH)','Miami (OH) RedHawks','MiamiOH'] },
  { abbr: 'MICH', name: 'Michigan Wolverines', aliases: ['MICH','Michigan','Michigan Wolverines'] },
  { abbr: 'MSU', name: 'Michigan State Spartans', aliases: ['MSU','Michigan State','Michigan State Spartans','MichiganState'] },
  { abbr: 'MTSU', name: 'Middle Tennessee Blue Raiders', aliases: ['MTSU','Middle Tennessee','Middle Tennessee Blue Raiders','MiddleTennessee'] },
  { abbr: 'MINN', name: 'Minnesota Golden Gophers', aliases: ['MINN','Minnesota','Minnesota Golden Gophers'] },
  { abbr: 'MSST', name: 'Mississippi State Bulldogs', aliases: ['MSST','Mississippi State','Mississippi State Bulldogs','MississippiState'] },
  { abbr: 'MIZ', name: 'Missouri Tigers', aliases: ['MIZ','Missouri','Missouri Tigers'] },
  { abbr: 'MOSU', name: 'Missouri State Bears', aliases: ['MOSU','Missouri State','Missouri State Bears','MissouriState'] },
  { abbr: 'NAVY', name: 'Navy Midshipmen', aliases: ['NAVY','Navy','Navy Midshipmen'] },
  { abbr: 'NCST', name: 'NC State Wolfpack', aliases: ['NC State','NC State Wolfpack','NCST','NCState'] },
  { abbr: 'NEB', name: 'Nebraska Cornhuskers', aliases: ['NEB','Nebraska','Nebraska Cornhuskers'] },
  { abbr: 'NEV', name: 'Nevada Wolf Pack', aliases: ['NEV','Nevada','Nevada Wolf Pack'] },
  { abbr: 'NICH', name: 'Nicholls Colonels', aliases: ['NICH','Nicholls','Nicholls Colonels','Nicholls St','Nicholls State','Nicholls State Colonels','Nicholls State University','Nicholls State University Colonels'] },
  { abbr: 'UNM', name: 'New Mexico Lobos', aliases: ['New Mexico','New Mexico Lobos','NewMexico','UNM'] },
  { abbr: 'NMSU', name: 'New Mexico State Aggies', aliases: ['NMSU','New Mexico State','New Mexico State Aggies','NewMexicoState'] },
  { abbr: 'UNC', name: 'North Carolina Tar Heels', aliases: ['North Carolina','North Carolina Tar Heels','NorthCarolina','UNC'] },
  { abbr: 'NDSU', name: 'North Dakota State Bison', aliases: ['NDSU','North Dakota State','North Dakota State Bison','North Dakota State University','North Dakota St','N Dakota State','N Dakota St','NorthDakotaState','NDSU Bison','Bison'] },
  { abbr: 'UNT', name: 'North Texas Mean Green', aliases: ['North Texas','North Texas Mean Green','NorthTexas','UNT'] },
  { abbr: 'NIU', name: 'Northern Illinois Huskies', aliases: ['NIU','Northern Illinois','Northern Illinois Huskies','NorthernIllinois'] },
  { abbr: 'NU', name: 'Northwestern Wildcats', aliases: ['NU','Northwestern','Northwestern Wildcats'] },
  { abbr: 'ND', name: 'Notre Dame Fighting Irish', aliases: ['ND','Notre Dame','Notre Dame Fighting Irish','NotreDame'] },
  { abbr: 'OHIO', name: 'Ohio Bobcats', aliases: ['OHIO','Ohio','Ohio Bobcats'] },
  { abbr: 'OSU', name: 'Ohio State Buckeyes', aliases: ['OSU','Ohio State Buckeyes','OhioState'] },
  { abbr: 'OU', name: 'Oklahoma Sooners', aliases: ['OU','Oklahoma','Oklahoma Sooners'] },
  { abbr: 'OKST', name: 'Oklahoma State Cowboys', aliases: ['OKST','Oklahoma State','Oklahoma State Cowboys','OklahomaState'] },
  { abbr: 'ODU', name: 'Old Dominion Monarchs', aliases: ['ODU','Old Dominion','Old Dominion Monarchs','OldDominion'] },
  { abbr: 'MISS', name: 'Ole Miss Rebels', aliases: ['MISS','Ole Miss','Ole Miss Rebels','OleMiss'] },
  { abbr: 'ORE', name: 'Oregon Ducks', aliases: ['ORE','Oregon','Oregon Ducks'] },
  { abbr: 'ORST', name: 'Oregon State Beavers', aliases: ['ORST','Oregon State','Oregon State Beavers','OregonState'] },
  { abbr: 'PSU', name: 'Penn State Nittany Lions', aliases: ['PSU','Penn State','Penn State Nittany Lions','PennState'] },
  { abbr: 'PITT', name: 'Pittsburgh Panthers', aliases: ['PITT','Pittsburgh','Pittsburgh Panthers'] },
  { abbr: 'PORST', name: 'Portland State Vikings', aliases: ['PORST','Portland State','Portland State Vikings','Portland State University','Portland St','Portland St Vikings'] },
  { abbr: 'PUR', name: 'Purdue Boilermakers', aliases: ['PUR','Purdue','Purdue Boilermakers'] },
  { abbr: 'RICE', name: 'Rice Owls', aliases: ['RICE','Rice','Rice Owls'] },
  { abbr: 'RICH', name: 'Richmond Spiders', aliases: ['RICH','Richmond','Richmond Spiders','University of Richmond'] },
  { abbr: 'RUTG', name: 'Rutgers Scarlet Knights', aliases: ['RUTG','Rutgers','Rutgers Scarlet Knights'] },
  { abbr: 'SAC', name: 'Sacramento State Hornets', aliases: ['SAC','Sacramento State','Sacramento State Hornets','Sacramento St','Sac St','Sac State','SacramentoState','CSUS'] },
  { abbr: 'MER', name: 'Mercer Bears', aliases: ['MER','Mercer','Mercer Bears'] },
  { abbr: 'PRST', name: 'Presbyterian Blue Hose', aliases: ['PRST','Presbyterian','Presbyterian Blue Hose'] },
  { abbr: 'SHSU', name: 'Sam Houston Bearkats', aliases: ['SHSU','Sam Houston Bearkats','SamHouston'] },
  { abbr: 'SAM', name: 'Samford Bulldogs', aliases: ['SAM','Samford','Samford Bulldogs','SamfordBulldogs'] },
  { abbr: 'SDSU', name: 'San Diego State Aztecs', aliases: ['SDSU','San Diego State','San Diego State Aztecs','SanDiegoState'] },
  { abbr: 'SJSU', name: 'San José State Spartans', aliases: ['SJSU','San José State','San José State Spartans','SanJoseState'] },
  { abbr: 'SMU', name: 'SMU Mustangs', aliases: ['SMU','SMU Mustangs'] },
  { abbr: 'USA', name: 'South Alabama Jaguars', aliases: ['South Alabama','South Alabama Jaguars','SouthAlabama','USA'] },
  { abbr: 'SC', name: 'South Carolina Gamecocks', aliases: ['SC','South Carolina','South Carolina Gamecocks','SouthCarolina'] },
  { abbr: 'SDST', name: 'South Dakota State Jackrabbits', aliases: ['SDST','S Dakota St','South Dakota St','South Dakota State','South Dakota State Jackrabbits','South Dakota State University','Jackrabbits'] },
  { abbr: 'USF', name: 'South Florida Bulls', aliases: ['South Florida','South Florida Bulls','SouthFlorida','USF'] },
  { abbr: 'USM', name: 'Southern Miss Golden Eagles', aliases: ['Southern Miss','Southern Miss Golden Eagles','SouthernMiss','USM'] },
  { abbr: 'STAN', name: 'Stanford Cardinal', aliases: ['STAN','Stanford','Stanford Cardinal'] },
  { abbr: 'STBK', name: 'Stony Brook Seawolves', aliases: ['STBK','SBU','Stony Brook','Stony Brook Seawolves','Stony Brook University','SUNY Stony Brook'] },
  { abbr: 'SYR', name: 'Syracuse Orange', aliases: ['SYR','Syracuse','Syracuse Orange'] },
  { abbr: 'TCU', name: 'TCU Horned Frogs', aliases: ['TCU','TCU Horned Frogs'] },
  { abbr: 'TEM', name: 'Temple Owls', aliases: ['TEM','Temple','Temple Owls'] },
  { abbr: 'TENN', name: 'Tennessee Volunteers', aliases: ['TENN','Tennessee','Tennessee Volunteers'] },
  { abbr: 'TOW', name: 'Towson Tigers', aliases: ['TOW','Towson','Towson Tigers','Towson University'] },
  { abbr: 'TEX', name: 'Texas Longhorns', aliases: ['TEX','Texas','Texas Longhorns'] },
  { abbr: 'TA&M', name: 'Texas A&M Aggies', aliases: ['TA&M','Texas A&M','Texas A&M Aggies','TexasAandM'] },
  { abbr: 'TXST', name: 'Texas State Bobcats', aliases: ['TXST','TXST Bobcats','TX State','Texas St','Texas St Bobcats','Texas State','Texas State Bobcats','Texas State University','Texas State University Bobcats','TexasState'] },
  { abbr: 'TTU', name: 'Texas Tech Red Raiders', aliases: ['TTU','Texas Tech','Texas Tech Red Raiders','TexasTech'] },
  { abbr: 'TOL', name: 'Toledo Rockets', aliases: ['TOL','Toledo','Toledo Rockets'] },
  { abbr: 'TROY', name: 'Troy Trojans', aliases: ['TROY','Troy','Troy Trojans','Troy University'] },
  { abbr: 'TULN', name: 'Tulane Green Wave', aliases: ['TULN','Tulane','Tulane Green Wave'] },
  { abbr: 'TLSA', name: 'Tulsa Golden Hurricane', aliases: ['TLSA','TUL','Tulsa','Tulsa Golden Hurricane','Tulsa University','University of Tulsa'] },
  { abbr: 'UAB', name: 'UAB Blazers', aliases: ['UAB','UAB Blazers'] },
  { abbr: 'UCF', name: 'UCF Knights', aliases: ['UCF','UCF Knights'] },
  { abbr: 'UCLA', name: 'UCLA Bruins', aliases: ['UCLA','UCLA Bruins'] },
  { abbr: 'CONN', name: 'UConn Huskies', aliases: ['CONN','UConn','UConn Huskies'] },
  { abbr: 'MASS', name: 'UMass Minutemen', aliases: ['MASS','UMass','UMass Minutemen'] },
  { abbr: 'UNLV', name: 'UNLV Rebels', aliases: ['UNLV','UNLV Rebels'] },
  { abbr: 'USC', name: 'USC Trojans', aliases: ['USC','USC Trojans'] },
  { abbr: 'UTSA', name: 'UTSA Roadrunners', aliases: ['UTSA','UTSA Roadrunners'] },
  { abbr: 'UTAH', name: 'Utah Utes', aliases: ['UTAH','Utah','Utah Utes'] },
  { abbr: 'UTU', name: 'Utah Tech Trailblazers', aliases: ['UTU','Utah Tech','Utah Tech Trailblazers','Utah Tech University','Dixie State','Dixie State Trailblazers'] },
  { abbr: 'UTM', name: 'UT Martin Skyhawks', aliases: ['UTM','UT Martin','UT-Martin','Tennessee-Martin','Tennessee Martin','University of Tennessee at Martin','UT Martin Skyhawks'] },
  { abbr: 'USU', name: 'Utah State Aggies', aliases: ['USU','Utah State','Utah State Aggies','UtahState'] },
  { abbr: 'UTEP', name: 'UTEP Miners', aliases: ['UTEP','UTEP Miners'] },
  { abbr: 'VAN', name: 'Vanderbilt Commodores', aliases: ['VAN','Vanderbilt','Vanderbilt Commodores'] },
  { abbr: 'VMI', name: 'VMI Keydets', aliases: ['VMI','Virginia Military Institute','Virginia Military Institute Keydets','VMI Keydets','Keydets'] },
  { abbr: 'WAG', name: 'Wagner Seahawks', aliases: ['WAG','Wagner','Wagner Seahawks','Wagner College','Wagner College Seahawks'] },
  { abbr: 'UVA', name: 'Virginia Cavaliers', aliases: ['UVA','Virginia','Virginia Cavaliers'] },
  { abbr: 'VT', name: 'Virginia Tech Hokies', aliases: ['VT','Virginia Tech','Virginia Tech Hokies','VirginiaTech'] },
  { abbr: 'WAKE', name: 'Wake Forest Demon Deacons', aliases: ['WAKE','Wake Forest','Wake Forest Demon Deacons','WakeForest'] },
  { abbr: 'WASH', name: 'Washington Huskies', aliases: ['WASH','Washington','Washington Huskies'] },
  { abbr: 'WSU', name: 'Washington State Cougars', aliases: ['WSU','Washington State','Washington State Cougars','WashingtonState'] },
  { abbr: 'WVU', name: 'West Virginia Mountaineers', aliases: ['WVU','West Virginia','West Virginia Mountaineers','WestVirginia'] },
  { abbr: 'W&M', name: 'William & Mary Tribe', aliases: ['W&M','WM','William & Mary','William and Mary','William & Mary Tribe','William and Mary Tribe','William & Mary College','College of William & Mary','Tribe'] },
  { abbr: 'WKU', name: 'Western Kentucky Hilltoppers', aliases: ['WKU','Western Kentucky Hilltoppers','WesternKentucky'] },
  { abbr: 'WMU', name: 'Western Michigan Broncos', aliases: ['WMU','Western Michigan','Western Michigan Broncos','WesternMichigan'] },
  { abbr: 'WIS', name: 'Wisconsin Badgers', aliases: ['WIS','Wisconsin','Wisconsin Badgers'] },
  { abbr: 'WYO', name: 'Wyoming Cowboys', aliases: ['WYO','Wyoming','Wyoming Cowboys'] },
]
;

const CFB_FBS_ALIAS_TO_ABBR: Record<string, string> = {
  '49ers': 'CLT',
  'a m': 'TA&M',
  'a-state': 'ARST',
  'apsu': 'APSU',
  'austin peay': 'APSU',
  'austin peay governors': 'APSU',
  'austin peay state': 'APSU',
  'austin peay state governors': 'APSU',
  'austin peay state university': 'APSU',
  'governors': 'APSU',
  'afa': 'AF',
  'air force': 'AF',
  'air force academy': 'AF',
  'air force falcons': 'AF',
  'akr': 'AKR',
  'akron': 'AKR',
  'akron zips': 'AKR',
  'ala': 'ALA',
  'alabama': 'ALA',
  'alabama crimson tide': 'ALA',
  'alabama-birmingham': 'UAB',
  'app': 'APP',
  'app state': 'APP',
  'appalachian': 'APP',
  'appalachian st': 'APP',
  'appalachian state': 'APP',
  'appalachian state mountaineers': 'APP',
  'ariz': 'ARIZ',
  'arizona': 'ARIZ',
  'arizona st': 'ASU',
  'arizona state': 'ASU',
  'arizona state sun devils': 'ASU',
  'arizona state university': 'ASU',
  'arizona wildcats': 'ARIZ',
  'ark': 'ARK',
  'arkansas': 'ARK',
  'arkansas razorbacks': 'ARK',
  'arkansas st': 'ARST',
  'arkansas state': 'ARST',
  'arkansas state red wolves': 'ARST',
  'army': 'ARMY',
  'army black knights': 'ARMY',
  'army west point': 'ARMY',
  'arst': 'ARST',
  'asu': 'ASU',
  'aub': 'AUB',
  'auburn': 'AUB',
  'auburn tigers': 'AUB',
  'auburn university': 'AUB',
  'awks': 'M-OH',
  'aztecs': 'SDSU',
  'badgers': 'WIS',
  'ball': 'BALL',
  'ball st': 'BALL',
  'ball state': 'BALL',
  'ball state cardinals': 'BALL',
  'ball state university': 'BALL',
  'bama': 'ALA',
  'bay': 'BAY',
  'baylor': 'BAY',
  'baylor bears': 'BAY',
  'baylor university': 'BAY',
  'bcu': 'BCU',
  'b-cu': 'BCU',
  'bethune-cookman': 'BCU',
  'bethune cookman': 'BCU',
  'bethune-cookman wildcats': 'BCU',
  'bethune cookman wildcats': 'BCU',
  'bethune-cookman university': 'BCU',
  'bc': 'BC',
  'bearcats': 'CIN',
  'bearkats': 'SHSU',
  'beavers': 'ORST',
  'berkeley': 'CAL',
  'bg': 'BGSU',
  'bgsu': 'BGSU',
  'black knights': 'ARMY',
  'blazers': 'UAB',
  'blue devils': 'DUKE',
  'blue raiders': 'MTSU',
  'boilermakers': 'PUR',
  'bois': 'BSU',
  'boise': 'BSU',
  'boise st': 'BSU',
  'boise state': 'BSU',
  'boise state broncos': 'BSU',
  'boston college': 'BC',
  'boston college eagles': 'BC',
  'boston college university': 'BC',
  'bowling green': 'BGSU',
  'bowling green falcons': 'BGSU',
  'bowling green state': 'BGSU',
  'bowling green state university': 'BGSU',
  'brigham young': 'BYU',
  'brigham young university': 'BYU',
  'bruins': 'UCLA',
  'bsu': 'BSU',
  'buckeyes': 'OSU',
  'buff': 'BUFF',
  'buffalo': 'BUFF',
  'buffalo bulls': 'BUFF',
  'buck': 'BUCK',
  'bucknell': 'BUCK',
  'bucknell bison': 'BUCK',
  'bucknell university': 'BUCK',
  'buffaloes': 'COLO',
  'buffs': 'COLO',
  'bulls': 'BUFF',
  'byu': 'BYU',
  'byu cougars': 'BYU',
  'cal': 'CAL',
  'california': 'CAL',
  'cal poly': 'CP',
  'cal poly mustangs': 'CP',
  'cal poly slo': 'CP',
  'cal poly san luis obispo': 'CP',
  'california polytechnic': 'CP',
  'california polytechnic state university': 'CP',
  'cp': 'CP',
  'california berkeley': 'CAL',
  'california golden bears': 'CAL',
  'california state university fresno': 'FRES',
  'cardinal': 'STAN',
  'cavaliers': 'UVA',
  'ccu': 'CCU',
  'central florida': 'UCF',
  'central mich': 'CMU',
  'central michigan': 'CMU',
  'central michigan chippewas': 'CMU',
  'central michigan university': 'CMU',
  'chanticleers': 'CCU',
  'chapel hill': 'UNC',
  'charlotte': 'CLT',
  'charlotte 49ers': 'CLT',
  'chippewas': 'CMU',
  'cin': 'CIN',
  'cincinnati': 'CIN',
  'cincinnati bearcats': 'CIN',
  'cincy': 'CIN',
  'clem': 'CLEM',
  'clemson': 'CLEM',
  'clemson tigers': 'CLEM',
  'clemson university': 'CLEM',
  'clt': 'CLT',
  'cmich': 'CMU',
  'cmu': 'CMU',
  'coastal': 'CCU',
  'coastal carolina': 'CCU',
  'coastal carolina chanticleers': 'CCU',
  'coastal carolina university': 'CCU',
  'colo': 'COLO',
  'colorado': 'COLO',
  'colorado boulder': 'COLO',
  'colorado buffaloes': 'COLO',
  'colorado st': 'CSU',
  'colorado state': 'CSU',
  'colorado state rams': 'CSU',
  'colorado state university': 'CSU',
  'commodores': 'VAN',
  'conn': 'CONN',
  'connecticut': 'CONN',
  'cornhuskers': 'NEB',
  'crimson tide': 'ALA',
  'csu': 'CSU',
  'csu fresno': 'FRES',
  'csu rams': 'CSU',
  'cu': 'COLO',
  'cuse': 'SYR',
  'cyclones': 'ISU',
  'del': 'DEL',
  'delaware': 'DEL',
  'delaware blue hens': 'DEL',
  'delaware fightin blue hens': 'DEL',
  'demon deacons': 'WAKE',
  'ducks': 'ORE',
  'duke': 'DUKE',
  'duke blue devils': 'DUKE',
  'duke university': 'DUKE',
  'dukes': 'JMU',
  'east carolina': 'ECU',
  'east carolina pirates': 'ECU',
  'east carolina university': 'ECU',
  'eastern mich': 'EMU',
  'eastern michigan': 'EMU',
  'eastern michigan eagles': 'EMU',
  'eastern michigan university': 'EMU',
  'ecu': 'ECU',
  'emich': 'EMU',
  'emu': 'EMU',
  'fau': 'FAU',
  'fightin blue hens': 'DEL',
  'fighting illini': 'ILL',
  'fighting irish': 'ND',
  'fiu': 'FIU',
  'fiu panthers': 'FIU',
  'fla': 'FLA',
  'flames': 'LIB',
  'florida': 'FLA',
  'florida atlantic': 'FAU',
  'florida atlantic owls': 'FAU',
  'florida atlantic university': 'FAU',
  'florida atlantic university owls': 'FAU',
  'fau owls': 'FAU',
  'fatl': 'FAU',
  'fla atl': 'FAU',
  'florida gators': 'FLA',
  'florida intl': 'FIU',
  'florida intl panthers': 'FIU',
  'florida international': 'FIU',
  'florida international panthers': 'FIU',
  'florida international university': 'FIU',
  'florida st': 'FSU',
  'florida state': 'FSU',
  'florida state seminoles': 'FSU',
  'florida state university': 'FSU',
  'fres': 'FRES',
  'fresno': 'FRES',
  'fresno st': 'FRES',
  'fresno state': 'FRES',
  'fresno state bulldogs': 'FRES',
  'fsu': 'FSU',
  'ga southern': 'GASO',
  'ga state': 'GAST',
  'ga tech': 'GT',
  'gaso': 'GASO',
  'gast': 'GAST',
  'gators': 'FLA',
  'georgia': 'UGA',
  'georgia bulldogs': 'UGA',
  'georgia institute of technology': 'GT',
  'georgia southern': 'GASO',
  'georgia southern eagles': 'GASO',
  'georgia southern university': 'GASO',
  'georgia st': 'GAST',
  'georgia state': 'GAST',
  'georgia state panthers': 'GAST',
  'georgia state university': 'GAST',
  'georgia tech': 'GT',
  'georgia tech yellow jackets': 'GT',
  'golden bears': 'CAL',
  'golden eagles': 'USM',
  'golden flashes': 'KENT',
  'golden gophers': 'MINN',
  'golden hurricane': 'TLSA',
  'green wave': 'TULN',
  'gt': 'GT',
  'haw': 'HAW',
  'hawaii': 'HAW',
  'hawaii rainbow warriors': 'HAW',
  'hawkeyes': 'IOWA',
  'hilltoppers': 'WKU',
  'hokies': 'VT',
  'hoosiers': 'IND',
  'horned frogs': 'TCU',
  'hou': 'HOU',
  'houston': 'HOU',
  'houston cougars': 'HOU',
  'how': 'HOW',
  'howard': 'HOW',
  'howard bison': 'HOW',
  'howard university': 'HOW',
  'hurricanes': 'MIA',
  'huskers': 'NEB',
  'icanes': 'MIA',
  'ill': 'ILL',
  'illinois': 'ILL',
  'illinois fighting illini': 'ILL',
  'illinois urbana-champaign': 'ILL',
  'ind': 'IND',
  'indiana': 'IND',
  'indiana hoosiers': 'IND',
  'indiana university': 'IND',
  'iowa': 'IOWA',
  'iow': 'IOWA',
  'iowa hawkeye': 'IOWA',
  'iowa hawkeyes': 'IOWA',
  'university of iowa': 'IOWA',
  'iowa st': 'ISU',
  'iowa state': 'ISU',
  'iowa state cyclones': 'ISU',
  'iowa state university': 'ISU',
  'irish': 'ND',
  'isu': 'ISU',
  'iu': 'IND',
  'jacksonville st': 'JVST',
  'jacksonville state': 'JVST',
  'jacksonville state gamecocks': 'JVST',
  'jaguars': 'USA',
  'james madison': 'JMU',
  'james madison dukes': 'JMU',
  'james madison university': 'JMU',
  'jax st': 'JVST',
  'jax state': 'JVST',
  'jayhawks': 'KU',
  'jmu': 'JMU',
  'jsu': 'JVST',
  'jvst': 'JVST',
  'k-state': 'KSU',
  'kansas': 'KU',
  'kansas jayhawks': 'KU',
  'kansas st': 'KSU',
  'kansas state': 'KSU',
  'kansas state university': 'KSU',
  'kansas state wildcats': 'KSU',
  'kenn': 'KENN',
  'kennesaw st': 'KENN',
  'kennesaw state': 'KENN',
  'kennesaw state owls': 'KENN',
  'kennesaw state university': 'KENN',
  'kent': 'KENT',
  'kent st': 'KENT',
  'kent state': 'KENT',
  'kent state golden flashes': 'KENT',
  'kent state university': 'KENT',
  'kentucky': 'UK',
  'kentucky wildcats': 'UK',
  'knights': 'UCF',
  'ksu': 'KSU',
  'ku': 'KU',
  'la tech': 'LT',
  'lib': 'LIB',
  'liberty': 'LIB',
  'liberty flames': 'LIB',
  'liberty university': 'LIB',
  'lobos': 'UNM',
  'longhorns': 'TEX',
  'lou': 'LOU',
  'louisiana': 'UL',
  'louisiana ragin cajuns': 'UL',
  'louisiana state': 'LSU',
  'louisiana state university': 'LSU',
  'louisiana tech': 'LT',
  'louisiana tech bulldogs': 'LT',
  'louisiana tech university': 'LT',
  'louisiana-lafayette': 'UL',
  'louisiana-monroe': 'ULM',
  'louisiana-monroe warhawks': 'ULM',
  'louisville': 'LOU',
  'louisville cardinals': 'LOU',
  'lsu': 'LSU',
  'lsu tigers': 'LSU',
  'lt': 'LT',
  'm-oh': 'M-OH',
  'marshall': 'MRSH',
  'marshall thundering herd': 'MRSH',
  'marshall university': 'MRSH',
  'maryland': 'MD',
  'maryland terrapins': 'MD',
  'mass': 'MASS',
  'massachusetts': 'MASS',
  'md': 'MD',
  'mean green': 'UNT',
  'mem': 'MEM',
  'memphis': 'MEM',
  'memphis tigers': 'MEM',
  'mia': 'MIA',
  'miami fl': 'MIA',
  'miami hurricanes': 'MIA',
  'miami oh': 'M-OH',
  'miami redhawks': 'M-OH',
  'miami university': 'M-OH',
  'miami-florida': 'MIA',
  'miami-ohio': 'M-OH',
  'mich': 'MICH',
  'mich state': 'MSU',
  'michigan': 'MICH',
  'michigan st': 'MSU',
  'michigan state': 'MSU',
  'michigan state spartans': 'MSU',
  'michigan state university': 'MSU',
  'michigan wolverines': 'MICH',
  'middle tenn': 'MTSU',
  'middle tennessee': 'MTSU',
  'middle tennessee blue raiders': 'MTSU',
  'middle tennessee state': 'MTSU',
  'middle tennessee state university': 'MTSU',
  'midshipmen': 'NAVY',
  'miners': 'UTEP',
  'minn': 'MINN',
  'minnesota': 'MINN',
  'minnesota golden gophers': 'MINN',
  'minutemen': 'MASS',
  'miss': 'MISS',
  'miss state': 'MSST',
  'mississippi': 'MISS',
  'mississippi st': 'MSST',
  'mississippi state': 'MSST',
  'mississippi state bulldogs': 'MSST',
  'mississippi state university': 'MSST',
  'missouri': 'MIZ',
  'missouri st': 'MOSU',
  'missouri state': 'MOSU',
  'missouri state bears': 'MOSU',
  'missouri state university': 'MOSU',
  'missouri tigers': 'MIZ',
  'miz': 'MIZ',
  'mizzou': 'MIZ',
  'mo state': 'MOSU',
  'monarchs': 'ODU',
  'monroe': 'ULM',
  'most': 'MOSU',
  'mrsh': 'MRSH',
  'msst': 'MSST',
  'msu': 'MSU',
  'mtsu': 'MTSU',
  'mustangs': 'SMU',
  'n illinois': 'NIU',
  'navy': 'NAVY',
  'navy midshipmen': 'NAVY',
  'nc st': 'NCST',
  'nc state': 'NCST',
  'nc state wolfpack': 'NCST',
  'ncst': 'NCST',
  'ncsu': 'NCST',
  'nd': 'ND',
  'neb': 'NEB',
  'nebraska': 'NEB',
  'nebraska cornhuskers': 'NEB',
  'nebraska-lincoln': 'NEB',
  'nev': 'NEV',
  'nevada': 'NEV',
  'nevada las vegas': 'UNLV',
  'nevada wolf pack': 'NEV',
  'nevada-reno': 'NEV',
  'new mexico': 'UNM',
  'new mexico lobos': 'UNM',
  'new mexico st': 'NMSU',
  'new mexico state': 'NMSU',
  'new mexico state aggies': 'NMSU',
  'new mexico state university': 'NMSU',
  'nittany lions': 'PSU',
  'niu': 'NIU',
  'niu huskies': 'NIU',
  'nm state': 'NMSU',
  'nmsu': 'NMSU',
  'north carolina': 'UNC',
  'north carolina state': 'NCST',
  'north carolina state university': 'NCST',
  'north carolina tar heels': 'UNC',
  'north texas': 'UNT',
  'north texas mean green': 'UNT',
  'northern illinois': 'NIU',
  'northern illinois huskies': 'NIU',
  'northern illinois university': 'NIU',
  'northwestern': 'NU',
  'northwestern university': 'NU',
  'northwestern wildcats': 'NU',
  'notre dame': 'ND',
  'notre dame fighting irish': 'ND',
  'nw': 'NU',
  'odu': 'ODU',
  'ohio': 'OHIO',
  'ohio bobcats': 'OHIO',
  'ohio st': 'OSU',
  'ohio state': 'OSU',
  'ohio state buckeyes': 'OSU',
  'ohio state university': 'OSU',
  'ohio u': 'OHIO',
  'ohio university': 'OHIO',
  'ok state': 'OKST',
  'okla': 'OU',
  'oklahoma': 'OU',
  'oklahoma sooners': 'OU',
  'oklahoma st': 'OKST',
  'oklahoma state': 'OKST',
  'oklahoma state cowboys': 'OKST',
  'oklahoma state university': 'OKST',
  'okst': 'OKST',
  'old dominion': 'ODU',
  'old dominion monarchs': 'ODU',
  'old dominion university': 'ODU',
  'ole miss': 'MISS',
  'ole miss rebels': 'MISS',
  'orange': 'SYR',
  'ore': 'ORE',
  'oregon': 'ORE',
  'oregon ducks': 'ORE',
  'oregon st': 'ORST',
  'oregon state': 'ORST',
  'oregon state beavers': 'ORST',
  'oregon state university': 'ORST',
  'orst': 'ORST',
  'osu': 'OSU',
  'penn st': 'PSU',
  'penn state': 'PSU',
  'penn state nittany lions': 'PSU',
  'pennsylvania state': 'PSU',
  'pennsylvania state university': 'PSU',
  'pirates': 'ECU',
  'pitt': 'PITT',
  'pitt panthers': 'PITT',
  'pittsburgh': 'PITT',
  'pittsburgh panthers': 'PITT',
  'porst': 'PORST',
  'portland st': 'PORST',
  'portland st vikings': 'PORST',
  'portland state': 'PORST',
  'portland state vikings': 'PORST',
  'portland state university': 'PORST',
  'psu': 'PSU',
  'pur': 'PUR',
  'purdue': 'PUR',
  'purdue boilermakers': 'PUR',
  'purdue university': 'PUR',
  'ragin cajuns': 'UL',
  'rainbow warriors': 'HAW',
  'rams': 'CSU',
  'razorbacks': 'ARK',
  'red raiders': 'TTU',
  'red wolves': 'ARST',
  'redhawks': 'M-OH',
  'rice': 'RICE',
  'rice owls': 'RICE',
  'rich': 'RICH',
  'richmond': 'RICH',
  'richmond spiders': 'RICH',
  'university of richmond': 'RICH',
  'rice university': 'RICE',
  'roadrunners': 'UTSA',
  'rockets': 'TOL',
  'rutg': 'RUTG',
  'rutgers': 'RUTG',
  'rutgers scarlet knights': 'RUTG',
  'rutgers university': 'RUTG',
  'rutgers-new brunswick': 'RUTG',
  'sam houston': 'SHSU',
  'sam houston bearkats': 'SHSU',
  'sam houston state': 'SHSU',
  'sam houston state university': 'SHSU',
  'san diego st': 'SDSU',
  'san diego state': 'SDSU',
  'san diego state aztecs': 'SDSU',
  'san diego state university': 'SDSU',
  'san jose st': 'SJSU',
  'san jose state': 'SJSU',
  'san jose state spartans': 'SJSU',
  'san jose state university': 'SJSU',
  'sc': 'SC',
  'scarlet knights': 'RUTG',
  'sdsu': 'SDSU',
  'seminoles': 'FSU',
  'shsu': 'SHSU',
  'sjsu': 'SJSU',
  'smu': 'SMU',
  'smu mustangs': 'SMU',
  'sooners': 'OU',
  'south alabama': 'USA',
  'south alabama jaguars': 'USA',
  'south carolina': 'SC',
  'south carolina gamecocks': 'SC',
  'sdst': 'SDST',
  's dakota st': 'SDST',
  'south dakota st': 'SDST',
  'south dakota state': 'SDST',
  'south dakota state jackrabbits': 'SDST',
  'south dakota state university': 'SDST',
  'jackrabbits': 'SDST',
  'camp': 'CAMP',
  'campbell': 'CAMP',
  'campbell fighting camels': 'CAMP',
  'campbell university': 'CAMP',
  'fighting camels': 'CAMP',
  'camels': 'CAMP',
  'tow': 'TOW',
  'towson': 'TOW',
  'towson tigers': 'TOW',
  'towson university': 'TOW',
  'south florida': 'USF',
  'south florida bulls': 'USF',
  'southern cal': 'USC',
  'southern california': 'USC',
  'southern methodist': 'SMU',
  'southern methodist university': 'SMU',
  'southern miss': 'USM',
  'southern miss golden eagles': 'USM',
  'southern mississippi': 'USM',
  'stan': 'STAN',
  'stanford': 'STAN',
  'stanford cardinal': 'STAN',
  'stbk': 'STBK',
  'sbu': 'STBK',
  'stony brook': 'STBK',
  'stony brook seawolves': 'STBK',
  'stony brook university': 'STBK',
  'suny stony brook': 'STBK',
  'stanford university': 'STAN',
  'state': 'MSST',
  'sun devils': 'ASU',
  'suny buffalo': 'BUFF',
  'syr': 'SYR',
  'syracuse': 'SYR',
  'syracuse orange': 'SYR',
  'syracuse university': 'SYR',
  'tamu': 'TA&M',
  'tar heels': 'UNC',
  'tcu': 'TCU',
  'tcu horned frogs': 'TCU',
  'tem': 'TEM',
  'temple': 'TEM',
  'temple owls': 'TEM',
  'temple university': 'TEM',
  'tenn': 'TENN',
  'tennessee': 'TENN',
  'tennessee vols': 'TENN',
  'tennessee volunteers': 'TENN',
  'terps': 'MD',
  'terrapins': 'MD',
  'tex': 'TEX',
  'texas': 'TEX',
  'texas a and m': 'TA&M',
  'texas a m': 'TA&M',
  'texas a m aggies': 'TA&M',
  'texas a m university': 'TA&M',
  'texas christian': 'TCU',
  'texas christian university': 'TCU',
  'texas longhorns': 'TEX',
  'texas st': 'TXST',
  'texas st bobcats': 'TXST',
  'texas state': 'TXST',
  'texas state bobcats': 'TXST',
  'texas state university': 'TXST',
  'texas state university bobcats': 'TXST',
  'tx state': 'TXST',
  'txst bobcats': 'TXST',
  'texas tech': 'TTU',
  'texas tech red raiders': 'TTU',
  'texas tech university': 'TTU',
  'texas-austin': 'TEX',
  'texas-el paso': 'UTEP',
  'texas-san antonio': 'UTSA',
  'th florida bulls': 'USF',
  'the u': 'MIA',
  'thundering herd': 'MRSH',
  'tlsa': 'TLSA',
  'tul': 'TLSA',
  'tol': 'TOL',
  'toledo': 'TOL',
  'toledo rockets': 'TOL',
  'troy': 'TROY',
  'troy trojans': 'TROY',
  'troy university': 'TROY',
  'ttu': 'TTU',
  'tulane': 'TULN',
  'tulane green wave': 'TULN',
  'tulane university': 'TULN',
  'tuln': 'TULN',
  'tulsa': 'TLSA',
  'tulsa golden hurricane': 'TLSA',
  'tulsa university': 'TLSA',
  'university of tulsa': 'TLSA',
  'txst': 'TXST',
  'u of l': 'LOU',
  'uab': 'UAB',
  'uab blazers': 'UAB',
  'uarizona': 'ARIZ',
  'ub': 'BUFF',
  'uc': 'CIN',
  'uc berkeley': 'CAL',
  'ucf': 'UCF',
  'ucf knights': 'UCF',
  'ucla': 'UCLA',
  'ucla bruins': 'UCLA',
  'uconn': 'CONN',
  'uconn huskies': 'CONN',
  'ud': 'DEL',
  'uf': 'FLA',
  'uga': 'UGA',
  'uiuc': 'ILL',
  'uk': 'UK',
  'ul': 'UL',
  'ul lafayette': 'UL',
  'ull': 'UL',
  'ulm': 'ULM',
  'umass': 'MASS',
  'umass amherst': 'MASS',
  'umass minutemen': 'MASS',
  'umd': 'MD',
  'unc': 'UNC',
  'unc chapel hill': 'UNC',
  'unc charlotte': 'CLT',
  'united states military academy': 'ARMY',
  'united states naval academy': 'NAVY',
  'university at buffalo': 'BUFF',
  'university of akron': 'AKR',
  'university of alabama': 'ALA',
  'university of alabama at birmingham': 'UAB',
  'university of arizona': 'ARIZ',
  'university of arkansas': 'ARK',
  'university of california berkeley': 'CAL',
  'university of california los angeles': 'UCLA',
  'university of central florida': 'UCF',
  'university of cincinnati': 'CIN',
  'university of colorado boulder': 'COLO',
  'university of connecticut': 'CONN',
  'university of delaware': 'DEL',
  'university of florida': 'FLA',
  'university of georgia': 'UGA',
  'university of hawaii': 'HAW',
  'university of houston': 'HOU',
  'university of illinois': 'ILL',
  'university of iowa': 'IOWA',
  'university of kansas': 'KU',
  'university of kentucky': 'UK',
  'university of louisiana at lafayette': 'UL',
  'university of louisiana monroe': 'ULM',
  'university of louisville': 'LOU',
  'university of maryland': 'MD',
  'university of massachusetts': 'MASS',
  'university of memphis': 'MEM',
  'university of miami': 'MIA',
  'university of michigan': 'MICH',
  'university of minnesota': 'MINN',
  'university of mississippi': 'MISS',
  'university of missouri': 'MIZ',
  'university of nebraska': 'NEB',
  'university of nevada las vegas': 'UNLV',
  'university of nevada reno': 'NEV',
  'university of new mexico': 'UNM',
  'university of north carolina': 'UNC',
  'university of north carolina at charlotte': 'CLT',
  'university of north texas': 'UNT',
  'university of notre dame': 'ND',
  'university of oklahoma': 'OU',
  'university of oregon': 'ORE',
  'university of pittsburgh': 'PITT',
  'university of south alabama': 'USA',
  'university of south carolina': 'SC',
  'university of south florida': 'USF',
  'university of southern california': 'USC',
  'university of southern mississippi': 'USM',
  'university of tennessee': 'TENN',
  'university of texas': 'TEX',
  'university of texas at el paso': 'UTEP',
  'university of texas at san antonio': 'UTSA',
  'university of toledo': 'TOL',
  'university of tulsa': 'TLSA',
  'university of utah': 'UTAH',
  'university of virginia': 'UVA',
  'university of washington': 'WASH',
  'university of wisconsin': 'WIS',
  'university of wyoming': 'WYO',
  'unl': 'NEB',
  'unlv': 'UNLV',
  'unlv rebels': 'UNLV',
  'unm': 'UNM',
  'unr': 'NEV',
  'unt': 'UNT',
  'uo': 'ORE',
  'us naval academy': 'NAVY',
  'usa': 'USA',
  'usafa': 'AF',
  'usc': 'USC',
  'usc trojans': 'USC',
  'usf': 'USF',
  'usm': 'USM',
  'usu': 'USU',
  'ut austin': 'TEX',
  'utah': 'UTAH',
  'utah st': 'USU',
  'utah state': 'USU',
  'utah state aggies': 'USU',
  'utah state university': 'USU',
  'utah utes': 'UTAH',
  'utu': 'UTU',
  'utah tech': 'UTU',
  'utah tech trailblazers': 'UTU',
  'utah tech university': 'UTU',
  'dixie state': 'UTU',
  'dixie state trailblazers': 'UTU',
  'utm': 'UTM',
  'ut martin': 'UTM',
  'ut-martin': 'UTM',
  'tennessee-martin': 'UTM',
  'tennessee martin': 'UTM',
  'university of tennessee at martin': 'UTM',
  'ut martin skyhawks': 'UTM',
  'utep': 'UTEP',
  'utep miners': 'UTEP',
  'utes': 'UTAH',
  'utsa': 'UTSA',
  'utsa roadrunners': 'UTSA',
  'uva': 'UVA',
  'va tech': 'VT',
  'van': 'VAN',
  'vanderbilt': 'VAN',
  'vanderbilt commodores': 'VAN',
  'vanderbilt university': 'VAN',
  'vandy': 'VAN',
  'virginia': 'UVA',
  'virginia cavaliers': 'UVA',
  'virginia polytechnic institute and state university': 'VT',
  'virginia tech': 'VT',
  'virginia tech hokies': 'VT',
  'vols': 'TENN',
  'volunteers': 'TENN',
  'vt': 'VT',
  'wake': 'WAKE',
  'wake forest': 'WAKE',
  'wake forest demon deacons': 'WAKE',
  'wake forest university': 'WAKE',
  'warhawks': 'ULM',
  'wash': 'WASH',
  'washington': 'WASH',
  'washington huskies': 'WASH',
  'washington st': 'WSU',
  'washington state': 'WSU',
  'washington state cougars': 'WSU',
  'washington state university': 'WSU',
  'wazzu': 'WSU',
  'west point': 'ARMY',
  'west virginia': 'WVU',
  'west virginia mountaineers': 'WVU',
  'west virginia university': 'WVU',
  'western kentucky': 'WKU',
  'western kentucky hilltoppers': 'WKU',
  'western kentucky university': 'WKU',
  'western ky': 'WKU',
  'western mich': 'WMU',
  'western michigan': 'WMU',
  'western michigan broncos': 'WMU',
  'western michigan university': 'WMU',
  'wisc': 'WIS',
  'wisconsin': 'WIS',
  'wisconsin badgers': 'WIS',
  'wisconsin-madison': 'WIS',
  'wku': 'WKU',
  'wmu': 'WMU',
  'wolverines': 'MICH',
  'wsu': 'WSU',
  'wvu': 'WVU',
  'w&m': 'W&M',
  'wm': 'W&M',
  'william & mary': 'W&M',
  'william and mary': 'W&M',
  'william & mary tribe': 'W&M',
  'william and mary tribe': 'W&M',
  'william & mary college': 'W&M',
  'college of william & mary': 'W&M',
  'tribe': 'W&M',
  'wyo': 'WYO',
  'wyoming': 'WYO',
  'wyoming cowboys': 'WYO',
  'yellow jackets': 'GT',
  'zips': 'AKR',
};

export function canonicalCfbTeam(value: any): CfbTeamDef | null {
  const input = value && typeof value === 'object'
    ? [value.school, value.name, value.displayName, value.shortDisplayName, value.shortName, value.abbr, value.abbreviation]
    : [value];

  for (const candidate of input) {
    const deRanked = String(candidate || '').replace(/\s*\(\s*\d+\s*\)\s*$/, '').trim();
    const normalized = normalizeText(deRanked);
    if (!normalized) continue;
    const aliasAbbr = CFB_FBS_ALIAS_TO_ABBR[normalized];
    if (aliasAbbr) {
      const exactAlias = CFB_TEAMS.find((team) => team.abbr === aliasAbbr);
      if (exactAlias) return exactAlias;
    }
    const exact = CFB_TEAMS.find((team) => normalizeText(team.abbr) === normalized || normalizeText(team.name) === normalized || team.aliases.some((alias) => normalizeText(alias) === normalized));
    if (exact) return exact;

    // Only match long labels, and choose the most specific alias. This avoids
    // short tokens such as "Ohio" or "Miami" accidentally capturing a
    // different school while still handling provider variants like "Jax St".
    if (normalized.replace(/ /g, '').length < 6) continue;
    const compact = normalized.replace(/ /g, '');
    let best: { team: CfbTeamDef; score: number } | null = null;
    for (const team of CFB_TEAMS) {
      const aliases = [team.name, ...team.aliases].map((alias) => normalizeText(alias)).filter((alias) => alias.replace(/ /g, '').length >= 6);
      for (const alias of aliases) {
        const aliasCompact = alias.replace(/ /g, '');
        const matches = normalized.includes(alias) || alias.includes(normalized) || compact.includes(aliasCompact) || aliasCompact.includes(compact);
        if (!matches) continue;
        const score = Math.min(compact.length, aliasCompact.length) * 10 + aliasCompact.length;
        if (!best || score > best.score) best = { team, score };
      }
    }
    if (best) return best.team;
  }
  return null;
}
